
package com.interhome.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "WebServiceSoap", targetNamespace = "http://www.interhome.com/webservice")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WebServiceSoap {


    /**
     * This method is used to Monitor if the WebService is available
     * 
     * @return
     *     returns com.interhome.webservice.CheckServerHealthResult
     */
    @WebMethod(operationName = "CheckServerHealth", action = "http://www.interhome.com/webservice/CheckServerHealth")
    @WebResult(name = "CheckServerHealthResult", targetNamespace = "http://www.interhome.com/webservice")
    @RequestWrapper(localName = "CheckServerHealth", targetNamespace = "http://www.interhome.com/webservice", className = "com.interhome.webservice.CheckServerHealth")
    @ResponseWrapper(localName = "CheckServerHealthResponse", targetNamespace = "http://www.interhome.com/webservice", className = "com.interhome.webservice.CheckServerHealthResponse")
    public CheckServerHealthResult checkServerHealth();

    /**
     * This method is used to Monitor if the WebService is available. The 'type' parameter defines what to perform.
     * 
     * @param type
     * @return
     *     returns com.interhome.webservice.CheckServerHealthResultV2
     */
    @WebMethod(operationName = "CheckServerHealthV2", action = "http://www.interhome.com/webservice/CheckServerHealthV2")
    @WebResult(name = "CheckServerHealthV2Result", targetNamespace = "http://www.interhome.com/webservice")
    @RequestWrapper(localName = "CheckServerHealthV2", targetNamespace = "http://www.interhome.com/webservice", className = "com.interhome.webservice.CheckServerHealthV2")
    @ResponseWrapper(localName = "CheckServerHealthV2Response", targetNamespace = "http://www.interhome.com/webservice", className = "com.interhome.webservice.CheckServerHealthV2Response")
    public CheckServerHealthResultV2 checkServerHealthV2(
        @WebParam(name = "type", targetNamespace = "http://www.interhome.com/webservice")
        String type);

    /**
     * Newsletter Request
     * 
     * @param inputValue
     * @return
     *     returns com.interhome.webservice.NewsletterReturnValue
     */
    @WebMethod(operationName = "Newsletter", action = "http://www.interhome.com/webservice/Newsletter")
    @WebResult(name = "NewsletterResult", targetNamespace = "http://www.interhome.com/webservice")
    @RequestWrapper(localName = "Newsletter", targetNamespace = "http://www.interhome.com/webservice", className = "com.interhome.webservice.Newsletter")
    @ResponseWrapper(localName = "NewsletterResponse", targetNamespace = "http://www.interhome.com/webservice", className = "com.interhome.webservice.NewsletterResponse")
    public NewsletterReturnValue newsletter(
        @WebParam(name = "inputValue", targetNamespace = "http://www.interhome.com/webservice")
        NewsletterInputValue inputValue);

    /**
     * AdditionalServices Request
     * 
     * @param inputValue
     * @return
     *     returns com.interhome.webservice.AdditionalServicesReturnValue
     */
    @WebMethod(operationName = "AdditionalServices", action = "http://www.interhome.com/webservice/AdditionalServices")
    @WebResult(name = "AdditionalServicesResult", targetNamespace = "http://www.interhome.com/webservice")
    @RequestWrapper(localName = "AdditionalServices", targetNamespace = "http://www.interhome.com/webservice", className = "com.interhome.webservice.AdditionalServices")
    @ResponseWrapper(localName = "AdditionalServicesResponse", targetNamespace = "http://www.interhome.com/webservice", className = "com.interhome.webservice.AdditionalServicesResponse")
    public AdditionalServicesReturnValue additionalServices(
        @WebParam(name = "inputValue", targetNamespace = "http://www.interhome.com/webservice")
        AdditionalServicesInputValue inputValue);

    /**
     * Availability Request
     * 
     * @param inputValue
     * @return
     *     returns com.interhome.webservice.AvailabilityRetunValue
     */
    @WebMethod(operationName = "Availability", action = "http://www.interhome.com/webservice/Availability")
    @WebResult(name = "AvailabilityResult", targetNamespace = "http://www.interhome.com/webservice")
    @RequestWrapper(localName = "Availability", targetNamespace = "http://www.interhome.com/webservice", className = "com.interhome.webservice.Availability")
    @ResponseWrapper(localName = "AvailabilityResponse", targetNamespace = "http://www.interhome.com/webservice", className = "com.interhome.webservice.AvailabilityResponse")
    public AvailabilityRetunValue availability(
        @WebParam(name = "inputValue", targetNamespace = "http://www.interhome.com/webservice")
        AvailabilityInputValue inputValue);

    /**
     * NearestBookingDate Request
     * 
     * @param inputValue
     * @return
     *     returns com.interhome.webservice.NearestBookingDateReturnValue
     */
    @WebMethod(operationName = "NearestBookingDate", action = "http://www.interhome.com/webservice/NearestBookingDate")
    @WebResult(name = "NearestBookingDateResult", targetNamespace = "http://www.interhome.com/webservice")
    @RequestWrapper(localName = "NearestBookingDate", targetNamespace = "http://www.interhome.com/webservice", className = "com.interhome.webservice.NearestBookingDate")
    @ResponseWrapper(localName = "NearestBookingDateResponse", targetNamespace = "http://www.interhome.com/webservice", className = "com.interhome.webservice.NearestBookingDateResponse")
    public NearestBookingDateReturnValue nearestBookingDate(
        @WebParam(name = "inputValue", targetNamespace = "http://www.interhome.com/webservice")
        NearestBookingDateInputValue inputValue);

    /**
     * PriceDetail Request
     * 
     * @param inputValue
     * @return
     *     returns com.interhome.webservice.PriceDetailRetunValue
     */
    @WebMethod(operationName = "PriceDetail", action = "http://www.interhome.com/webservice/PriceDetail")
    @WebResult(name = "PriceDetailResult", targetNamespace = "http://www.interhome.com/webservice")
    @RequestWrapper(localName = "PriceDetail", targetNamespace = "http://www.interhome.com/webservice", className = "com.interhome.webservice.PriceDetail")
    @ResponseWrapper(localName = "PriceDetailResponse", targetNamespace = "http://www.interhome.com/webservice", className = "com.interhome.webservice.PriceDetailResponse")
    public PriceDetailRetunValue priceDetail(
        @WebParam(name = "inputValue", targetNamespace = "http://www.interhome.com/webservice")
        PriceDetailInputValue inputValue);

    /**
     * Prices Request
     * 
     * @param inputValue
     * @return
     *     returns com.interhome.webservice.PricesRetunValue
     */
    @WebMethod(operationName = "Prices", action = "http://www.interhome.com/webservice/Prices")
    @WebResult(name = "PricesResult", targetNamespace = "http://www.interhome.com/webservice")
    @RequestWrapper(localName = "Prices", targetNamespace = "http://www.interhome.com/webservice", className = "com.interhome.webservice.Prices")
    @ResponseWrapper(localName = "PricesResponse", targetNamespace = "http://www.interhome.com/webservice", className = "com.interhome.webservice.PricesResponse")
    public PricesRetunValue prices(
        @WebParam(name = "inputValue", targetNamespace = "http://www.interhome.com/webservice")
        PricesInputValue inputValue);

    /**
     * PriceList Request
     * 
     * @param inputValue
     * @return
     *     returns com.interhome.webservice.PriceListReturnValue
     */
    @WebMethod(operationName = "PriceList", action = "http://www.interhome.com/webservice/PriceList")
    @WebResult(name = "PriceListResult", targetNamespace = "http://www.interhome.com/webservice")
    @RequestWrapper(localName = "PriceList", targetNamespace = "http://www.interhome.com/webservice", className = "com.interhome.webservice.PriceList")
    @ResponseWrapper(localName = "PriceListResponse", targetNamespace = "http://www.interhome.com/webservice", className = "com.interhome.webservice.PriceListResponse")
    public PriceListReturnValue priceList(
        @WebParam(name = "inputValue", targetNamespace = "http://www.interhome.com/webservice")
        PriceListInputValue inputValue);

    /**
     * ClientBooking Request
     * 
     * @param inputValue
     * @return
     *     returns com.interhome.webservice.ClientBookingReturnValue
     */
    @WebMethod(operationName = "ClientBooking", action = "http://www.interhome.com/webservice/ClientBooking")
    @WebResult(name = "ClientBookingResult", targetNamespace = "http://www.interhome.com/webservice")
    @RequestWrapper(localName = "ClientBooking", targetNamespace = "http://www.interhome.com/webservice", className = "com.interhome.webservice.ClientBooking")
    @ResponseWrapper(localName = "ClientBookingResponse", targetNamespace = "http://www.interhome.com/webservice", className = "com.interhome.webservice.ClientBookingResponse")
    public ClientBookingReturnValue clientBooking(
        @WebParam(name = "inputValue", targetNamespace = "http://www.interhome.com/webservice")
        ClientBookingInputValue inputValue);

    /**
     * RetailerBooking Request
     * 
     * @param inputValue
     * @return
     *     returns com.interhome.webservice.RetailerBookingReturnValue
     */
    @WebMethod(operationName = "RetailerBooking", action = "http://www.interhome.com/webservice/RetailerBooking")
    @WebResult(name = "RetailerBookingResult", targetNamespace = "http://www.interhome.com/webservice")
    @RequestWrapper(localName = "RetailerBooking", targetNamespace = "http://www.interhome.com/webservice", className = "com.interhome.webservice.RetailerBooking")
    @ResponseWrapper(localName = "RetailerBookingResponse", targetNamespace = "http://www.interhome.com/webservice", className = "com.interhome.webservice.RetailerBookingResponse")
    public RetailerBookingReturnValue retailerBooking(
        @WebParam(name = "inputValue", targetNamespace = "http://www.interhome.com/webservice")
        RetailerBookingInputValue inputValue);

    /**
     * ReadBooking Request
     * 
     * @param inputValue
     * @return
     *     returns com.interhome.webservice.ReadBookingReturnValue
     */
    @WebMethod(operationName = "ReadBooking", action = "http://www.interhome.com/webservice/ReadBooking")
    @WebResult(name = "ReadBookingResult", targetNamespace = "http://www.interhome.com/webservice")
    @RequestWrapper(localName = "ReadBooking", targetNamespace = "http://www.interhome.com/webservice", className = "com.interhome.webservice.ReadBooking")
    @ResponseWrapper(localName = "ReadBookingResponse", targetNamespace = "http://www.interhome.com/webservice", className = "com.interhome.webservice.ReadBookingResponse")
    public ReadBookingReturnValue readBooking(
        @WebParam(name = "inputValue", targetNamespace = "http://www.interhome.com/webservice")
        ReadBookingInputValue inputValue);

    /**
     * RatifyBooking Request
     * 
     * @param inputValue
     * @return
     *     returns com.interhome.webservice.RatifyBookingReturnValue
     */
    @WebMethod(operationName = "RatifyBooking", action = "http://www.interhome.com/webservice/RatifyBooking")
    @WebResult(name = "RatifyBookingResult", targetNamespace = "http://www.interhome.com/webservice")
    @RequestWrapper(localName = "RatifyBooking", targetNamespace = "http://www.interhome.com/webservice", className = "com.interhome.webservice.RatifyBooking")
    @ResponseWrapper(localName = "RatifyBookingResponse", targetNamespace = "http://www.interhome.com/webservice", className = "com.interhome.webservice.RatifyBookingResponse")
    public RatifyBookingReturnValue ratifyBooking(
        @WebParam(name = "inputValue", targetNamespace = "http://www.interhome.com/webservice")
        RatifyBookingInputValue inputValue);

    /**
     * CancelBooking Request
     * 
     * @param inputValue
     * @return
     *     returns com.interhome.webservice.CancelBookingReturnValue
     */
    @WebMethod(operationName = "CancelBooking", action = "http://www.interhome.com/webservice/CancelBooking")
    @WebResult(name = "CancelBookingResult", targetNamespace = "http://www.interhome.com/webservice")
    @RequestWrapper(localName = "CancelBooking", targetNamespace = "http://www.interhome.com/webservice", className = "com.interhome.webservice.CancelBooking")
    @ResponseWrapper(localName = "CancelBookingResponse", targetNamespace = "http://www.interhome.com/webservice", className = "com.interhome.webservice.CancelBookingResponse")
    public CancelBookingReturnValue cancelBooking(
        @WebParam(name = "inputValue", targetNamespace = "http://www.interhome.com/webservice")
        CancelBookingInputValue inputValue);

    /**
     * CheckBooking Request
     * 
     * @param inputValue
     * @return
     *     returns com.interhome.webservice.CheckBookingReturnValue
     */
    @WebMethod(operationName = "CheckBooking", action = "http://www.interhome.com/webservice/CheckBooking")
    @WebResult(name = "CheckBookingResult", targetNamespace = "http://www.interhome.com/webservice")
    @RequestWrapper(localName = "CheckBooking", targetNamespace = "http://www.interhome.com/webservice", className = "com.interhome.webservice.CheckBooking")
    @ResponseWrapper(localName = "CheckBookingResponse", targetNamespace = "http://www.interhome.com/webservice", className = "com.interhome.webservice.CheckBookingResponse")
    public CheckBookingReturnValue checkBooking(
        @WebParam(name = "inputValue", targetNamespace = "http://www.interhome.com/webservice")
        CheckBookingInputValue inputValue);

    /**
     * CancellationConditions Request
     * 
     * @param inputValue
     * @return
     *     returns com.interhome.webservice.CancellationConditionReturnValue
     */
    @WebMethod(operationName = "CancellationConditions", action = "http://www.interhome.com/webservice/CancellationConditions")
    @WebResult(name = "CancellationConditionsResult", targetNamespace = "http://www.interhome.com/webservice")
    @RequestWrapper(localName = "CancellationConditions", targetNamespace = "http://www.interhome.com/webservice", className = "com.interhome.webservice.CancellationConditions")
    @ResponseWrapper(localName = "CancellationConditionsResponse", targetNamespace = "http://www.interhome.com/webservice", className = "com.interhome.webservice.CancellationConditionsResponse")
    public CancellationConditionReturnValue cancellationConditions(
        @WebParam(name = "inputValue", targetNamespace = "http://www.interhome.com/webservice")
        CancellationConditionInputValue inputValue);

    /**
     * Search Request
     * 
     * @param inputValue
     * @return
     *     returns com.interhome.webservice.SearchReturnValue
     */
    @WebMethod(operationName = "Search", action = "http://www.interhome.com/webservice/Search")
    @WebResult(name = "SearchResult", targetNamespace = "http://www.interhome.com/webservice")
    @RequestWrapper(localName = "Search", targetNamespace = "http://www.interhome.com/webservice", className = "com.interhome.webservice.Search")
    @ResponseWrapper(localName = "SearchResponse", targetNamespace = "http://www.interhome.com/webservice", className = "com.interhome.webservice.SearchResponse")
    public SearchReturnValue search(
        @WebParam(name = "inputValue", targetNamespace = "http://www.interhome.com/webservice")
        SearchInputValue inputValue);

    /**
     * Accommodation details Request
     * 
     * @param inputValue
     * @return
     *     returns com.interhome.webservice.AccommodationDetailReturnValue
     */
    @WebMethod(operationName = "AccommodationDetail", action = "http://www.interhome.com/webservice/AccommodationDetail")
    @WebResult(name = "AccommodationDetailResult", targetNamespace = "http://www.interhome.com/webservice")
    @RequestWrapper(localName = "AccommodationDetail", targetNamespace = "http://www.interhome.com/webservice", className = "com.interhome.webservice.AccommodationDetail")
    @ResponseWrapper(localName = "AccommodationDetailResponse", targetNamespace = "http://www.interhome.com/webservice", className = "com.interhome.webservice.AccommodationDetailResponse")
    public AccommodationDetailReturnValue accommodationDetail(
        @WebParam(name = "inputValue", targetNamespace = "http://www.interhome.com/webservice")
        AccommodationDetailInputValue inputValue);

    /**
     * Trips Request
     * 
     * @param inputValue
     * @return
     *     returns com.interhome.webservice.TripsReturnValue
     */
    @WebMethod(operationName = "Trips", action = "http://www.interhome.com/webservice/Trips")
    @WebResult(name = "TripsResult", targetNamespace = "http://www.interhome.com/webservice")
    @RequestWrapper(localName = "Trips", targetNamespace = "http://www.interhome.com/webservice", className = "com.interhome.webservice.Trips")
    @ResponseWrapper(localName = "TripsResponse", targetNamespace = "http://www.interhome.com/webservice", className = "com.interhome.webservice.TripsResponse")
    public TripsReturnValue trips(
        @WebParam(name = "inputValue", targetNamespace = "http://www.interhome.com/webservice")
        TripsInputValue inputValue);

    /**
     * AffiliateDetail Request
     * 
     * @param inputValue
     * @return
     *     returns com.interhome.webservice.AffiliateDetailReturnValue
     */
    @WebMethod(operationName = "AffiliateDetail", action = "http://www.interhome.com/webservice/AffiliateDetail")
    @WebResult(name = "AffiliateDetailResult", targetNamespace = "http://www.interhome.com/webservice")
    @RequestWrapper(localName = "AffiliateDetail", targetNamespace = "http://www.interhome.com/webservice", className = "com.interhome.webservice.AffiliateDetail")
    @ResponseWrapper(localName = "AffiliateDetailResponse", targetNamespace = "http://www.interhome.com/webservice", className = "com.interhome.webservice.AffiliateDetailResponse")
    public AffiliateDetailReturnValue affiliateDetail(
        @WebParam(name = "inputValue", targetNamespace = "http://www.interhome.com/webservice")
        AffiliateDetailInputValue inputValue);

    /**
     * VoucherDetail Request
     * 
     * @param inputValue
     * @return
     *     returns com.interhome.webservice.VoucherDetailReturnValue
     */
    @WebMethod(operationName = "VoucherDetail", action = "http://www.interhome.com/webservice/VoucherDetail")
    @WebResult(name = "VoucherDetailResult", targetNamespace = "http://www.interhome.com/webservice")
    @RequestWrapper(localName = "VoucherDetail", targetNamespace = "http://www.interhome.com/webservice", className = "com.interhome.webservice.VoucherDetail")
    @ResponseWrapper(localName = "VoucherDetailResponse", targetNamespace = "http://www.interhome.com/webservice", className = "com.interhome.webservice.VoucherDetailResponse")
    public VoucherDetailReturnValue voucherDetail(
        @WebParam(name = "inputValue", targetNamespace = "http://www.interhome.com/webservice")
        VoucherDetailInputValue inputValue);

    /**
     * PaymentInformation Request
     * 
     * @param inputValue
     * @return
     *     returns com.interhome.webservice.PaymentInformationReturnValue
     */
    @WebMethod(operationName = "PaymentExtInformation", action = "http://www.interhome.com/webservice/PaymentExtInformation")
    @WebResult(name = "PaymentExtInformationResult", targetNamespace = "http://www.interhome.com/webservice")
    @RequestWrapper(localName = "PaymentExtInformation", targetNamespace = "http://www.interhome.com/webservice", className = "com.interhome.webservice.PaymentExtInformation")
    @ResponseWrapper(localName = "PaymentExtInformationResponse", targetNamespace = "http://www.interhome.com/webservice", className = "com.interhome.webservice.PaymentExtInformationResponse")
    public PaymentInformationReturnValue paymentExtInformation(
        @WebParam(name = "inputValue", targetNamespace = "http://www.interhome.com/webservice")
        PaymentInformationInputValue inputValue);

}
